AY2223S2-CS2103T-T13-3/tp

docs/team/huixuant.md
=> Add Hui Xuan's skeletal PPP

docs/UserGuide.md
Closes #22 
Update User Guide for delete feature.
=> Update delete feature in UG

docs/UserGuide.md
Add instructions for using the Edit command in UG
=> Add Edit command in UG

docs/UserGuide.md
Oops, forgot to edit Header. Editted it now!
=> Made some Edit to the Edit UG

docs/UserGuide.md
=> Update help and clear features in UG

docs/DeveloperGuide.md
=> Update Developer Guide for v1.1

docs/UserGuide.md
=> Add find, list user guides.

docs/DeveloperGuide.md
Fixed some minor grammar mistakes.
=> Edit some grammar in DG

src/main/resources/view/CommandBox.fxml, src/main/resources/view/DarkTheme.css, src/main/resources/view/MainWindow.fxml, src/main/resources/view/ResultDisplay.fxml
* Shift `CommandBox` and `ResultDisplay` to the bottom of the window 
* Update styles of `CommandBox` and `ResultDisplay` to better align with mockup
=> Update Javafx Ui

src/main/java/seedu/address/model/application/UniqueApplicationList.java
=> Fix bug that prevents user from editing status of existing application

src/main/java/seedu/address/logic/commands/ClearApplicationCommand.java, src/main/java/seedu/address/logic/parser/InternshipBookParser.java
=> Add Clear Applications command

docs/DeveloperGuide.md
- Add implementation details for sort feature
- Add use case for sort feature
- Add user stories for features that will be implemented in v1.3
Closes #102
=> Improve DG for v1.3

src/main/java/seedu/address/logic/parser/AddApplicationCommandParser.java, src/main/java/seedu/address/logic/parser/ApplicationParserUtil.java, src/main/java/seedu/address/storage/ApplicationStorageManager.java, src/test/java/seedu/address/logic/ApplicationLogicManagerTest.java, src/test/java/seedu/address/logic/commands/ApplicationCommandTestUtil.java, src/test/java/seedu/address/logic/parser/AddApplicationCommandParserTest.java, src/test/java/seedu/address/logic/parser/ApplicationCommandParserTestUtil.java, src/test/java/seedu/address/logic/parser/ApplicationParserUtilTest.java, src/test/java/seedu/address/logic/parser/InternshipBookParserTest.java, src/test/java/seedu/address/testutil/TypicalApplications.java, src/test/java/seedu/address/testutil/TypicalIndexes.java
Closes #134 #135 
Progress for #136
=> Add tests related to parsing

src/main/java/seedu/address/ui/HelpCommand.java, src/main/java/seedu/address/ui/HelpWindow.java, src/main/resources/view/HelpWindow.css, src/main/resources/view/HelpWindow.fxml
=> Improve Help window

src/main/java/seedu/address/ui/HelpCommand.java, src/main/java/seedu/address/ui/HelpWindow.java, src/main/resources/view/HelpWindow.fxml
Closes #94.
This feature is finalised together with UG to align the commands and their respective formats.
=> Add more help commands in help window

src/main/java/seedu/address/logic/commands/AddTaskCommand.java, src/main/java/seedu/address/logic/commands/EditTaskCommand.java, src/main/java/seedu/address/logic/parser/ApplicationParserUtil.java, src/main/java/seedu/address/model/application/Application.java, src/main/java/seedu/address/model/task/Deadline.java, src/main/java/seedu/address/model/task/Task.java, src/main/java/seedu/address/storage/JsonAdaptedApplication.java, src/main/java/seedu/address/ui/ApplicationCard.java
=> Modify Deadline restriction

src/main/java/seedu/sprint/logic/commands/FindCommand.java, src/main/java/seedu/sprint/logic/parser/FindCommandParser.java, src/main/java/seedu/sprint/model/application/NameContainsKeywordsPredicate.java, src/main/java/seedu/sprint/ui/HelpWindow.java
Resolves #216.
Find command adjustments
It now supports:
1. find keywords(s)
2. find [r/keyword(s)] [c/keyword(s)] [s/keyword(s)]
It throws errors for:
find keywords [r/keyword(s)] [c/keyword(s)] [s/keyword(s)]
=> Fix help window and find command problems

docs/team/huixuant.md
Fill in previous skeletal PPP with draft content
=> Create draft of Hui Xuan's PPP

src/main/java/seedu/sprint/logic/commands/SortCommand.java, src/test/java/seedu/sprint/logic/commands/ApplicationCommandTestUtil.java, src/test/java/seedu/sprint/logic/commands/FindCommandTest.java, src/test/java/seedu/sprint/logic/commands/ListCommandIntegrationTest.java, src/test/java/seedu/sprint/logic/commands/ListCommandTest.java, src/test/java/seedu/sprint/logic/commands/SortCommandTest.java, src/test/java/seedu/sprint/logic/parser/InternshipBookParserTest.java, src/test/java/seedu/sprint/logic/parser/SortCommandParserTest.java
Add test cases for:
- List Command
- Sort Command
- Sort Command Parser
Also, decoupled Sort Command from Undo Command
=> Add test cases for Sort, List commands

docs/UserGuide.md
Mostly minor fixes only. 
@noahxinjie Please add to the portion on how applications are sorted alphabetically if both role and company name are the same.
=> UG Final run through

docs/team/xyluschen.md, src/main/java/seedu/sprint/logic/commands/AddTaskCommand.java, src/main/java/seedu/sprint/logic/commands/DeleteTaskCommand.java, src/main/java/seedu/sprint/logic/commands/EditTaskCommand.java, src/test/data/JsonSerializableInternshipBookTest/typicalApplicationsInternshipBook.json, src/test/java/seedu/sprint/logic/commands/ApplicationCommandTestUtil.java, src/test/java/seedu/sprint/testutil/TypicalApplications.java
Closes #273. 
@huixuant Please check through my fixes for the 3 task-related commands. Thank you!
=> Important changes and fixes

docs/DeveloperGuide.md, docs/index.md
And add page breaks for pdf conversion
=> Update DG and Product Page (Acknowledgements) 

docs/UserGuide.md
=> Add scenarios for edit and delete task

docs/UserGuide.md
=> Add user scenarios for edit-app and delete-app

docs/UserGuide.md
=> UG updates
